# This is the .toml file passed to Locomotion.
# For information on the different settings available, and an example file,
# see the Locomotion README: https://github.com/leoncvlt/loconotion/blob/master/README.md

# DO NOT CHANGE THIS VALUE. The deploy script relies on the site being deployed to the
# "site" directory.
name = "Squad 2022 Batch Trip"

# This page should be the root of your website. It's important.
page = "https://osnaren.notion.site/Soliton-Squad-2022-Batch-Trip-f656426c11f546798c8fce97247a1c08"
